return {
  { 'i',  '~/.config/nvim/init.lua' },
  { 'e',  '~/notes' },
  { 'K',  '~/.config/nvim/base-config/keys.vim' },
  { 'r',  '~/.config/karabiner.edn' },
  { 't',  '~/.config/kitty/kitty.conf' },
  { 'T',  '~/.tmux.conf' },
  { 'h',  '~/.hammerspoon/init.lua' },
  { 'z',  '~/.zshrc' },
  { 'sc', '/opt/repos/frontend/libs/spark/src/common/scss/mixins/_colors.scss' },
  { 'sf', '/opt/repos/frontend/libs/spark/src/common/scss/mixins/_fonts.scss' },
  '/opt/repos/frontend/reactUi',
  '/opt/repos/ondemand',
  '/opt/repos/frontend/libs/spark',
  '/opt/repos/xm-api',
  '/opt/repos/xm-openapi-specs',
  '/opt/repos/xm-database',
  '/opt/repos/xm-ss-gen',
  '/opt/repos/builtin-script-steps',
  '/opt/repos/qa-automation-ui',
  '/opt/repos/qa-automation',
  '/opt/repos/http',
  '/opt/repos/gitlab-merge-requests.spoon.proj',
  '/opt/repos/customer-config-ui-feature-definition/features.json',
  '/opt/repos/xm-api/src/main/java/com/xmatters/xm/repositories/FeatureToggleRepository.java',
  '/opt/repos/qmk_firmware/keyboards/handwired/dactyl_manuform/5x6/keymaps/MagicDuck/keymap.c',
  '~/notes/.obsidian.vimrc',
  '/Users/stephanbadragan/Library/Application Support/lazygit/config.yml'
}
