-- require('my.plugins.theme.default')
return {
  -- require('my.plugins.theme.tinted'),
  -- require('my.plugins.theme.gruvbox'),
  -- require('my.plugins.theme.nightfox'),
  require('my.plugins.theme.github'),
  -- require('my.plugins.theme.catpuccin'),
  -- require('my.plugins.theme.onedark'),
  -- require('my.plugins.theme.dracula'),
  -- require('my.plugins.theme.zenbones'),
  -- require('my.plugins.theme.cyberdream'),

  {
    'xiyaowong/transparent.nvim',
    lazy = false, -- make sure we load this during startup
    priority = 1000, -- make sure to load this before all the other start plugins
    enabled = not vim.env.PROF,
    config = function()
      require('transparent').setup({
        extra_groups = {
          -- 'menubarBaseBg',
          -- 'menubarBg1',
          -- 'menubarBg2',
          -- 'menubarBg3',
          -- 'menubarBg4',
          -- 'DiffChange'
        },
        exclude_groups = { 'Comment', 'CursorLine', 'CursorLineNr' },
      })

      vim.cmd('TransparentEnable')
    end,
  },

  -- {
  --   'MrSloth-dev/Switcheroo.nvim',
  --   dependencies = {
  --     'rktjmp/lush.nvim',
  --     'rktjmp/lush.nvim',
  --     'nvim-telescope/telescope.nvim',
  --     'sontungexpt/witch',
  --     'Abstract-IDE/Abstract-cs',
  --     'tomasiser/vim-code-dark',
  --     'Mofiqul/vscode.nvim',
  --     'marko-cerovac/material.nvim',
  --     'bluz71/vim-nightfly-colors',
  --     'bluz71/vim-moonfly-colors',
  --     'ChristianChiarulli/nvcode-color-schemes.vim',
  --     'folke/tokyonight.nvim',
  --     'comfysage/evergarden',
  --     'sainnhe/sonokai',
  --     'nyoom-engineering/oxocarbon.nvim',
  --     'kyazdani42/blue-moon',
  --     'mhartington/oceanic-next',
  --     'nvimdev/zephyr-nvim',
  --     'rockerBOO/boo-colorscheme-nvim',
  --     'jim-at-jibba/ariake.nvim',
  --     'ishan9299/modus-theme-vim',
  --     'sainnhe/edge',
  --     'theniceboy/nvim-deus',
  --     'PHSix/nvim-hybrid',
  --     'Th3Whit3Wolf/space-nvim',
  --     'yonlu/omni.vim',
  --     'ray-x/aurora',
  --     'tanvirtin/monokai.nvim',
  --     'ofirgall/ofirkai.nvim',
  --     'savq/melange-nvim',
  --     'fenetikm/falcon',
  --     'andersevenrud/nordic.nvim',
  --     'AlexvZyl/nordic.nvim',
  --     'shaunsingh/nord.nvim',
  --     'ishan9299/nvim-solarized-lua',
  --     'jthvai/lavender.nvim',
  --     'navarasu/onedark.nvim',
  --     'sainnhe/gruvbox-material',
  --     'sainnhe/everforest',
  --     'neanias/everforest-nvim',
  --     'NTBBloodbath/doom-one.nvim',
  --     'dracula/vim',
  --     'Mofiqul/dracula.nvim',
  --     'niyabits/calvera-dark.nvim',
  --     'nxvu699134/vn-night.nvim',
  --     'adisen99/codeschool.nvim',
  --     'projekt0n/github-nvim-theme',
  --     'kdheepak/monochrome.nvim',
  --     'rose-pine/neovim',
  --     'zenbones-theme/zenbones.nvim',
  --     'catppuccin/nvim',
  --     'FrenzyExists/aquarium-vim',
  --     'EdenEast/nightfox.nvim',
  --     'kvrohit/substrata.nvim',
  --     'ldelossa/vimdark',
  --     'Everblush/nvim',
  --     'adisen99/apprentice.nvim',
  --     'olimorris/onedarkpro.nvim',
  --     'rmehri01/onenord.nvim',
  --     'RishabhRD/gruvy',
  --     'luisiacc/gruvbox-baby',
  --     'titanzero/zephyrium',
  --     'rebelot/kanagawa.nvim',
  --     'sho-87/kanagawa-paper.nvim',
  --     'kevinm6/kurayami.nvim',
  --     'tiagovla/tokyodark.nvim',
  --     'cpea2506/one_monokai.nvim',
  --     'phha/zenburn.nvim',
  --     'kvrohit/rasmus.nvim',
  --     'chrsm/paramount-ng.nvim',
  --     'qaptoR-nvim/chocolatier.nvim',
  --     'rockyzhang24/arctic.nvim',
  --     'ramojus/mellifluous.nvim',
  --     'Yazeed1s/minimal.nvim',
  --     'Mofiqul/adwaita.nvim',
  --     'olivercederborg/poimandres.nvim',
  --     'mellow-theme/mellow.nvim',
  --     'gbprod/nord.nvim',
  --     'Yazeed1s/oh-lucy.nvim',
  --     'embark-theme/vim',
  --     'nyngwang/nvimgelion',
  --     'maxmx03/fluoromachine.nvim',
  --     'dasupradyumna/midnight.nvim',
  --     'uncleTen276/dark_flat.nvim',
  --     'zootedb0t/citruszest.nvim',
  --     'xero/miasma.nvim',
  --     'Verf/deepwhite.nvim',
  --     'judaew/ronny.nvim',
  --     'ribru17/bamboo.nvim',
  --     'cryptomilk/nightcity.nvim',
  --     'polirritmico/monokai-nightasty.nvim',
  --     'oxfist/night-owl.nvim',
  --     'miikanissi/modus-themes.nvim',
  --     'alexmozaidze/palenight.nvim',
  --     'scottmckendry/cyberdream.nvim',
  --     'HoNamDuong/hybrid.nvim',
  --     'bartekjaszczak/distinct-nvim',
  --     'samharju/synthweave.nvim',
  --     'ptdewey/darkearth-nvim',
  --     'uloco/bluloco.nvim',
  --     'slugbyte/lackluster.nvim',
  --     '0xstepit/flow.nvim',
  --     'samharju/serene.nvim',
  --     'killitar/obscure.nvim',
  --     'bakageddy/alduin.nvim',
  --     'diegoulloao/neofusion.nvim',
  --     'bartekjaszczak/luma-nvim',
  --     'bartekjaszczak/finale-nvim',
  --     'ellisonleao/gruvbox.nvim',
  --     'metalelf0/jellybeans-nvim',
  --     'lalitmee/cobalt2.nvim',
  --     'calind/selenized.nvim',
  --   },
  --   opts = {},
  -- },
}
