format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$sudo\
$line_break\
$character"""

right_format = """
$conda\
$python\
$nodejs\
$cmd_duration"""
command_timeout = 1000

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
# format = "[$branch]($style) "
# style = "bright-black"
format = "[$symbol$branch(:$remote_branch)]($style)"
style = "dark-black"
symbol =  "󰘬 "

[git_status]
# format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](red) ($ahead_behind$stashed)]($style)"
style = "bold green"
# conflicted = "​"
# untracked = "​"
# modified = "​"
# staged = "​"
# renamed = "​"
# deleted = "​"
# stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
