require("my/global/init")
require("my/config/options")
vim.cmd([[ source ~/.config/nvim/lua/my/config/base-keymaps.vim ]])
require("my/config/keymaps")
require("my/config/commands")
require("my/config/autocommands")
require("my/config/lazy")
